version: '2'
services:
  server:
    image: smart-server:v0.1.0
    container_name: smart-server
    restart: always
    networks:
      - smart
  web:
    image: smart-web:v0.1.0
    container_name: smart-web
    restart: always
    ports:
      - 8888:80
    networks:
      - smart
    depends_on:
      - server
networks:
  smart:
    external: false